### PR TITLE
Public friendly readme

### PR DESCRIPTION
**Pull request by m09**
This repository will be used by participants during the workshop, let's have a public friendly readme and handle organization in the issues :slightly_smiling_face:

### CODE REVIEW

**Comment by EgorBu** [comment]
Good idea and thanks for the explanation!
Just to clarify - do you want to keep all these long docs in issues?

I think it could be more convenient to store them in `org`/`details` directory - so we can refer to a specific line of a document during the discussion - and discussions in issues will look much compact.
WDYT, @m09?

**Comment by m09** [comment]
Storing in a separate folder is a good idea :+1: I'll edit the PR

**Review by bzz — APPROVED** [review]
Looks great, @m09  @EgorBu thank you for putting it together!

Having `/docs/` also sounds very good.

**Review by EgorBu — APPROVED** [review]

**Comment by m09** [comment]
I've put the original text, modified with what I'm doing for dev and project similarity in `docs`, please discuss my choices if you have different ideas! Merging for now since we have other PRs based on this one and we can discuss after merge.

**Pull request merged**
